import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { 
  GeistPixelSquare, 
  GeistPixelGrid, 
  GeistPixelCircle, 
  GeistPixelTriangle, 
  GeistPixelLine 
} from "geist/font/pixel";
import "./globals.css";

const geistSans = GeistSans;
const geistMono = GeistMono;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
